/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Annotation {
  'id' : string,
  'title' : string,
  'body' : string,
  'tags' : Array<string>,
  'authorNote' : string,
  'timestamp' : bigint,
}
export interface AspectEvent {
  'orb' : number,
  'aspectType' : string,
  'timestamp' : bigint,
  'body1' : string,
  'body2' : string,
}
export interface CorrelationResult {
  'pearsonCoefficient' : number,
  'significance' : string,
  'dataPoints' : bigint,
}
export interface LivePrice {
  'change24h' : number,
  'value' : number,
  'lastUpdated' : bigint,
  'marketId' : string,
  'changePct24h' : number,
}
export interface MarketDataPoint {
  'value' : number,
  'volume' : number,
  'marketId' : string,
  'timestamp' : bigint,
}
export interface MoonPhase {
  'illumination' : number,
  'timestamp' : bigint,
  'phase' : string,
}
export interface PlanetaryPosition {
  'latitude' : number,
  'body' : string,
  'distance' : number,
  'longitude' : number,
  'timestamp' : bigint,
}
export interface Stats {
  'totalAspects' : bigint,
  'totalMarketPoints' : bigint,
  'totalPositions' : bigint,
  'totalPhases' : bigint,
  'totalAnnotations' : bigint,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'addAnnotation' : ActorMethod<[Annotation], undefined>,
  'addAspects' : ActorMethod<[Array<AspectEvent>], undefined>,
  'addMarketDataBatch' : ActorMethod<[Array<MarketDataPoint>], undefined>,
  'addMoonPhases' : ActorMethod<[Array<MoonPhase>], undefined>,
  'addPlanetaryPositions' : ActorMethod<[Array<PlanetaryPosition>], undefined>,
  'computeCorrelation' : ActorMethod<
    [string, string, bigint, bigint],
    CorrelationResult
  >,
  'deleteAnnotation' : ActorMethod<[string], undefined>,
  'fetchBtcDominance' : ActorMethod<[], undefined>,
  'fetchBtcPrice' : ActorMethod<[], undefined>,
  'fetchEthPrice' : ActorMethod<[], undefined>,
  'fetchFearGreedIndex' : ActorMethod<[], undefined>,
  'fetchLiveMarketData' : ActorMethod<[], undefined>,
  'fetchTotalMcap' : ActorMethod<[], undefined>,
  'getAnnotations' : ActorMethod<[bigint, bigint], Array<Annotation>>,
  'getAspects' : ActorMethod<
    [string, string, bigint, bigint],
    Array<AspectEvent>
  >,
  'getLastFetchTime' : ActorMethod<[], bigint>,
  'getLiveMarketSnapshot' : ActorMethod<[], Array<LivePrice>>,
  'getMarketData' : ActorMethod<
    [string, bigint, bigint],
    Array<MarketDataPoint>
  >,
  'getMoonPhases' : ActorMethod<[bigint, bigint], Array<MoonPhase>>,
  'getPlanetaryPositions' : ActorMethod<
    [string, bigint, bigint],
    Array<PlanetaryPosition>
  >,
  'getStats' : ActorMethod<[], Stats>,
  'getTopCorrelations' : ActorMethod<
    [bigint, bigint],
    Array<CorrelationResult>
  >,
  'seedData' : ActorMethod<[], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateAnnotation' : ActorMethod<[string, Annotation], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];