/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Annotation = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'authorNote' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const AspectEvent = IDL.Record({
  'orb' : IDL.Float64,
  'aspectType' : IDL.Text,
  'timestamp' : IDL.Int,
  'body1' : IDL.Text,
  'body2' : IDL.Text,
});
export const MarketDataPoint = IDL.Record({
  'value' : IDL.Float64,
  'volume' : IDL.Float64,
  'marketId' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const MoonPhase = IDL.Record({
  'illumination' : IDL.Float64,
  'timestamp' : IDL.Int,
  'phase' : IDL.Text,
});
export const PlanetaryPosition = IDL.Record({
  'latitude' : IDL.Float64,
  'body' : IDL.Text,
  'distance' : IDL.Float64,
  'longitude' : IDL.Float64,
  'timestamp' : IDL.Int,
});
export const CorrelationResult = IDL.Record({
  'pearsonCoefficient' : IDL.Float64,
  'significance' : IDL.Text,
  'dataPoints' : IDL.Int,
});
export const LivePrice = IDL.Record({
  'change24h' : IDL.Float64,
  'value' : IDL.Float64,
  'lastUpdated' : IDL.Int,
  'marketId' : IDL.Text,
  'changePct24h' : IDL.Float64,
});
export const Stats = IDL.Record({
  'totalAspects' : IDL.Nat,
  'totalMarketPoints' : IDL.Nat,
  'totalPositions' : IDL.Nat,
  'totalPhases' : IDL.Nat,
  'totalAnnotations' : IDL.Nat,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'addAnnotation' : IDL.Func([Annotation], [], []),
  'addAspects' : IDL.Func([IDL.Vec(AspectEvent)], [], []),
  'addMarketDataBatch' : IDL.Func([IDL.Vec(MarketDataPoint)], [], []),
  'addMoonPhases' : IDL.Func([IDL.Vec(MoonPhase)], [], []),
  'addPlanetaryPositions' : IDL.Func([IDL.Vec(PlanetaryPosition)], [], []),
  'computeCorrelation' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Int, IDL.Int],
      [CorrelationResult],
      ['query'],
    ),
  'deleteAnnotation' : IDL.Func([IDL.Text], [], []),
  'fetchBtcDominance' : IDL.Func([], [], []),
  'fetchBtcPrice' : IDL.Func([], [], []),
  'fetchEthPrice' : IDL.Func([], [], []),
  'fetchFearGreedIndex' : IDL.Func([], [], []),
  'fetchLiveMarketData' : IDL.Func([], [], []),
  'fetchTotalMcap' : IDL.Func([], [], []),
  'getAnnotations' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(Annotation)],
      ['query'],
    ),
  'getAspects' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Int, IDL.Int],
      [IDL.Vec(AspectEvent)],
      ['query'],
    ),
  'getLastFetchTime' : IDL.Func([], [IDL.Int], ['query']),
  'getLiveMarketSnapshot' : IDL.Func([], [IDL.Vec(LivePrice)], ['query']),
  'getMarketData' : IDL.Func(
      [IDL.Text, IDL.Int, IDL.Int],
      [IDL.Vec(MarketDataPoint)],
      ['query'],
    ),
  'getMoonPhases' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(MoonPhase)],
      ['query'],
    ),
  'getPlanetaryPositions' : IDL.Func(
      [IDL.Text, IDL.Int, IDL.Int],
      [IDL.Vec(PlanetaryPosition)],
      ['query'],
    ),
  'getStats' : IDL.Func([], [Stats], ['query']),
  'getTopCorrelations' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(CorrelationResult)],
      ['query'],
    ),
  'seedData' : IDL.Func([], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateAnnotation' : IDL.Func([IDL.Text, Annotation], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Annotation = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'authorNote' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const AspectEvent = IDL.Record({
    'orb' : IDL.Float64,
    'aspectType' : IDL.Text,
    'timestamp' : IDL.Int,
    'body1' : IDL.Text,
    'body2' : IDL.Text,
  });
  const MarketDataPoint = IDL.Record({
    'value' : IDL.Float64,
    'volume' : IDL.Float64,
    'marketId' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const MoonPhase = IDL.Record({
    'illumination' : IDL.Float64,
    'timestamp' : IDL.Int,
    'phase' : IDL.Text,
  });
  const PlanetaryPosition = IDL.Record({
    'latitude' : IDL.Float64,
    'body' : IDL.Text,
    'distance' : IDL.Float64,
    'longitude' : IDL.Float64,
    'timestamp' : IDL.Int,
  });
  const CorrelationResult = IDL.Record({
    'pearsonCoefficient' : IDL.Float64,
    'significance' : IDL.Text,
    'dataPoints' : IDL.Int,
  });
  const LivePrice = IDL.Record({
    'change24h' : IDL.Float64,
    'value' : IDL.Float64,
    'lastUpdated' : IDL.Int,
    'marketId' : IDL.Text,
    'changePct24h' : IDL.Float64,
  });
  const Stats = IDL.Record({
    'totalAspects' : IDL.Nat,
    'totalMarketPoints' : IDL.Nat,
    'totalPositions' : IDL.Nat,
    'totalPhases' : IDL.Nat,
    'totalAnnotations' : IDL.Nat,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'addAnnotation' : IDL.Func([Annotation], [], []),
    'addAspects' : IDL.Func([IDL.Vec(AspectEvent)], [], []),
    'addMarketDataBatch' : IDL.Func([IDL.Vec(MarketDataPoint)], [], []),
    'addMoonPhases' : IDL.Func([IDL.Vec(MoonPhase)], [], []),
    'addPlanetaryPositions' : IDL.Func([IDL.Vec(PlanetaryPosition)], [], []),
    'computeCorrelation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Int, IDL.Int],
        [CorrelationResult],
        ['query'],
      ),
    'deleteAnnotation' : IDL.Func([IDL.Text], [], []),
    'fetchBtcDominance' : IDL.Func([], [], []),
    'fetchBtcPrice' : IDL.Func([], [], []),
    'fetchEthPrice' : IDL.Func([], [], []),
    'fetchFearGreedIndex' : IDL.Func([], [], []),
    'fetchLiveMarketData' : IDL.Func([], [], []),
    'fetchTotalMcap' : IDL.Func([], [], []),
    'getAnnotations' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(Annotation)],
        ['query'],
      ),
    'getAspects' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Int, IDL.Int],
        [IDL.Vec(AspectEvent)],
        ['query'],
      ),
    'getLastFetchTime' : IDL.Func([], [IDL.Int], ['query']),
    'getLiveMarketSnapshot' : IDL.Func([], [IDL.Vec(LivePrice)], ['query']),
    'getMarketData' : IDL.Func(
        [IDL.Text, IDL.Int, IDL.Int],
        [IDL.Vec(MarketDataPoint)],
        ['query'],
      ),
    'getMoonPhases' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(MoonPhase)],
        ['query'],
      ),
    'getPlanetaryPositions' : IDL.Func(
        [IDL.Text, IDL.Int, IDL.Int],
        [IDL.Vec(PlanetaryPosition)],
        ['query'],
      ),
    'getStats' : IDL.Func([], [Stats], ['query']),
    'getTopCorrelations' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(CorrelationResult)],
        ['query'],
      ),
    'seedData' : IDL.Func([], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateAnnotation' : IDL.Func([IDL.Text, Annotation], [], []),
  });
};

export const init = ({ IDL }) => { return []; };