/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface LivePrice {
    change24h: number;
    value: number;
    lastUpdated: bigint;
    marketId: string;
    changePct24h: number;
}
export interface CorrelationResult {
    pearsonCoefficient: number;
    significance: string;
    dataPoints: bigint;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface PlanetaryPosition {
    latitude: number;
    body: string;
    distance: number;
    longitude: number;
    timestamp: bigint;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface Annotation {
    id: string;
    title: string;
    body: string;
    tags: Array<string>;
    authorNote: string;
    timestamp: bigint;
}
export interface Stats {
    totalAspects: bigint;
    totalMarketPoints: bigint;
    totalPositions: bigint;
    totalPhases: bigint;
    totalAnnotations: bigint;
}
export interface MarketDataPoint {
    value: number;
    volume: number;
    marketId: string;
    timestamp: bigint;
}
export interface AspectEvent {
    orb: number;
    aspectType: string;
    timestamp: bigint;
    body1: string;
    body2: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface MoonPhase {
    illumination: number;
    timestamp: bigint;
    phase: string;
}
export interface backendInterface {
    addAnnotation(annotation: Annotation): Promise<void>;
    addAspects(aspects: Array<AspectEvent>): Promise<void>;
    addMarketDataBatch(batch: Array<MarketDataPoint>): Promise<void>;
    addMoonPhases(phases: Array<MoonPhase>): Promise<void>;
    addPlanetaryPositions(positions: Array<PlanetaryPosition>): Promise<void>;
    computeCorrelation(marketId: string, astroSeriesId: string, startTime: bigint, endTime: bigint): Promise<CorrelationResult>;
    deleteAnnotation(id: string): Promise<void>;
    fetchBtcDominance(): Promise<void>;
    fetchBtcPrice(): Promise<void>;
    fetchEthPrice(): Promise<void>;
    fetchFearGreedIndex(): Promise<void>;
    fetchLiveMarketData(): Promise<void>;
    fetchTotalMcap(): Promise<void>;
    getAnnotations(start: bigint, end: bigint): Promise<Array<Annotation>>;
    getAspects(body: string, aspectType: string, start: bigint, end: bigint): Promise<Array<AspectEvent>>;
    getLastFetchTime(): Promise<bigint>;
    getLiveMarketSnapshot(): Promise<Array<LivePrice>>;
    getMarketData(marketId: string, start: bigint, end: bigint): Promise<Array<MarketDataPoint>>;
    getMoonPhases(start: bigint, end: bigint): Promise<Array<MoonPhase>>;
    getPlanetaryPositions(body: string, start: bigint, end: bigint): Promise<Array<PlanetaryPosition>>;
    getStats(): Promise<Stats>;
    getTopCorrelations(startTime: bigint, endTime: bigint): Promise<Array<CorrelationResult>>;
    seedData(): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateAnnotation(id: string, updated: Annotation): Promise<void>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAnnotation(arg0: Annotation): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAnnotation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAnnotation(arg0);
            return result;
        }
    }
    async addAspects(arg0: Array<AspectEvent>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAspects(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAspects(arg0);
            return result;
        }
    }
    async addMarketDataBatch(arg0: Array<MarketDataPoint>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMarketDataBatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMarketDataBatch(arg0);
            return result;
        }
    }
    async addMoonPhases(arg0: Array<MoonPhase>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMoonPhases(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMoonPhases(arg0);
            return result;
        }
    }
    async addPlanetaryPositions(arg0: Array<PlanetaryPosition>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPlanetaryPositions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPlanetaryPositions(arg0);
            return result;
        }
    }
    async computeCorrelation(arg0: string, arg1: string, arg2: bigint, arg3: bigint): Promise<CorrelationResult> {
        if (this.processError) {
            try {
                const result = await this.actor.computeCorrelation(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.computeCorrelation(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async deleteAnnotation(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAnnotation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAnnotation(arg0);
            return result;
        }
    }
    async fetchBtcDominance(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchBtcDominance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchBtcDominance();
            return result;
        }
    }
    async fetchBtcPrice(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchBtcPrice();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchBtcPrice();
            return result;
        }
    }
    async fetchEthPrice(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchEthPrice();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchEthPrice();
            return result;
        }
    }
    async fetchFearGreedIndex(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchFearGreedIndex();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchFearGreedIndex();
            return result;
        }
    }
    async fetchLiveMarketData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchLiveMarketData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchLiveMarketData();
            return result;
        }
    }
    async fetchTotalMcap(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchTotalMcap();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchTotalMcap();
            return result;
        }
    }
    async getAnnotations(arg0: bigint, arg1: bigint): Promise<Array<Annotation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnnotations(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnnotations(arg0, arg1);
            return result;
        }
    }
    async getAspects(arg0: string, arg1: string, arg2: bigint, arg3: bigint): Promise<Array<AspectEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAspects(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAspects(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async getLastFetchTime(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getLastFetchTime();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLastFetchTime();
            return result;
        }
    }
    async getLiveMarketSnapshot(): Promise<Array<LivePrice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLiveMarketSnapshot();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLiveMarketSnapshot();
            return result;
        }
    }
    async getMarketData(arg0: string, arg1: bigint, arg2: bigint): Promise<Array<MarketDataPoint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarketData(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarketData(arg0, arg1, arg2);
            return result;
        }
    }
    async getMoonPhases(arg0: bigint, arg1: bigint): Promise<Array<MoonPhase>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMoonPhases(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMoonPhases(arg0, arg1);
            return result;
        }
    }
    async getPlanetaryPositions(arg0: string, arg1: bigint, arg2: bigint): Promise<Array<PlanetaryPosition>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlanetaryPositions(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlanetaryPositions(arg0, arg1, arg2);
            return result;
        }
    }
    async getStats(): Promise<Stats> {
        if (this.processError) {
            try {
                const result = await this.actor.getStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStats();
            return result;
        }
    }
    async getTopCorrelations(arg0: bigint, arg1: bigint): Promise<Array<CorrelationResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopCorrelations(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopCorrelations(arg0, arg1);
            return result;
        }
    }
    async seedData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedData();
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateAnnotation(arg0: string, arg1: Annotation): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAnnotation(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAnnotation(arg0, arg1);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
